name: Storybook

on:
  push:
    branches:
      - master

jobs:
  storybook:
    runs-on: ubuntu-latest
    name: Build Storybook
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: true

      - name: Build modules
        run: pnpm build

      - name: Build storybook
        run: |
          pnpm lerna run --scope @gorules/jdm-editor build:storybook
          touch packages/jdm-editor/docs/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: packages/jdm-editor/docs
          CLEAN: true
          FORCE: true
